const NAVIGATION_SCREEN_NAME = {
  HOME_SCREEN: 'HOME_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  DASHBOARD: 'DASHBOARD',
  INTROSCREEN: 'INTROSCREEN',
  INSTAGRAM: 'INSTAGRAM',
  GLASSMORPHISM: 'GLASSMORPHISM',
  GYROSCOPE_SCREEN: 'GYROSCOPE_SCREEN',
};

export default NAVIGATION_SCREEN_NAME;
